### ISSUE TITLE
No option to fix file path errors when original file path is changed and error opening the emulator

### ISSUE THREAD

**Issue by fuser-invent** [NiceneNerd/UKMM#214]
Using the newest build "0.15.0 - 2024-08-29" on a Wiindows 11 computer. This started with me looking at why the open emulator button wasn't working. When clicked it would very briefly flash a terminal window and then close it. After timing it to try to capture a screenshot, I finally got this:

![Screenshot 2024-09-01 215210](https://github.com/user-attachments/assets/e35bcbf9-bb0a-470e-887c-74d6493bdf35)

I thought that I likely needed to change the file path to not have a space between Cemu and Emulator in the first folder, so I added an underscore "Cemu_Emulator". I went into the Settings menu and update all of the file paths, but everything else in UKMM is still looking for the old file paths. If I try to change anything with any mod I get this error:

![image](https://github.com/user-attachments/assets/ac0cb8ac-90bd-438d-a30f-4d7006088833)

Additionally, the Open Emulator button is no longer shown. Deleting the ukmm-x86_64-pc-windows-msvc folder and using a new one solves all the file path errors. Although I still had a problem when clicking the open emulator button, this time it asked me if I wanted to select a custom path and I pointed it to the new location, and it worked. It's possible this could be consolidated with the issue I submitted [being unable to uninstall a mod](https://github.com/NiceneNerd/UKMM/issues/213), because it also solved that problem. It doesn't solve the "Migrate from BCML" file path issue though.

**Comment by NiceneNerd** [comment]
Do you mean you moved UKMM's stuff? Do you already change the storage path in UKMM's settings?

**Comment by fuser-invent** [comment]
For this issue submission it is renaming any folder in the file path that causes the problem. Ex. Changing “Z:\Cemu Emulator\” to “Z:\Cemu_Emulator\” or “Z:\Cemu\”

Yes, I changed all the file paths in UKMM’s settings to reflect the above change.

UKMM can not open the file because it continues to look for it in the original “Z:\Cemu Emulator\” location and does not change to looking for it in the “Z:\Cemu_Emulator\” location.

**Comment by NiceneNerd** [comment]
Does this persist after restarting UKMM? Also, post your settings file.

**Comment by fuser-invent** [comment]
Yes, it did persist after restarting UKMM. The issue was temporarily solved by extracting a fresh UKMM package and replacing the old one, clicking on the Open Emulator button, then choosing Custom Path in the pop-up and setting the new directory.

I tried to recreate this solution and it did not work a second time, all file paths are still pointing to an old install location.

The pop-up did not show in the old UKMM install, even after restarting it. Example of old file path:

```
current_mode: WiiU
system_7z: true
storage_dir: Z:\Cemu_Emulator
check_updates: Stable
show_changelog: true
last_version: 0.15.0
wiiu_config:
  language: USen
  profile: BenjaZ
  dump:
    bin_type: Nintendo
    source:
      type: Unpacked
      host_path: Z:\Cemu_Emulator\Cemu_Emulator_Backup\mlc01\usr\title
      content_dir: Z:\Cemu_Emulator\Cemu_Emulator_Backup\mlc01\usr\title\00050000\101c9400\content
      update_dir: Z:\Cemu_Emulator\Cemu_Emulator_Backup\mlc01\usr\title\0005000e\101c9400\content
      aoc_dir: Z:\Cemu_Emulator\Cemu_Emulator_Backup\mlc01\usr\title\0005000c\101c9400\content\0010
  deploy_config:
    output: Z:\Cemu_Emulator\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM
    method: Copy
    auto: true
    cemu_rules: true
    executable: Z:\Cemu_Emulator\cemu_1.26.2\Cemu.exe
switch_config: null
```

Example of new changed file path:
```
current_mode: WiiU
system_7z: true
storage_dir: Z:\Cemu-Emulator
check_updates: Stable
show_changelog: true
last_version: null
wiiu_config:
  language: USen
  profile: Default
  dump:
    bin_type: Nintendo
    source:
      type: Unpacked
      host_path: Z:\Cemu-Emulator\Cemu_Emulator_Backup\mlc01\usr\title
      content_dir: Z:\Cemu-Emulator\Cemu_Emulator_Backup\mlc01\usr\title\00050000\101c9400\content
      update_dir: Z:\Cemu-Emulator\Cemu_Emulator_Backup\mlc01\usr\title\00050000e\101c9400\content
      aoc_dir: Z:\Cemu-Emulator\Cemu_Emulator_Backup\mlc01\usr\title\0005000c\101c9400\content\0010
  deploy_config:
    output: Z:\Cemu-Emulator\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM
    method: Copy
    auto: false
    cemu_rules: false
    executable: Z:\Cemu-Emulator\cemu_1.26.2\Cemu.exe
switch_config: null
```

To recreate the issue:

1. Change the name the root folder that Cemu is located in to anything.
2. Open **Cemu.exe**
2. Choose **Select a custom path** and update to the new file path:
![image](https://github.com/user-attachments/assets/fa7bbe8c-9bed-4f59-a256-4d25c9ca2486)
3. Go to **Options -> General settings** in Cemu and update the **Game Paths**
4. Open UKMM, go to **settings tab**, and update all the file paths to reflect the above change.
5. Close and restart UKMM.
6. Attempt to make any change to the mod list.
7. Receive file path error.

Only solution I've found to fix these issues:

1. Delete the following folders:
- ukmm-x86_64-pc-windows-msvc (extracted ukmm zip)
- C:\Users\benja\AppData\Local\ukmm
- C:\Users\benja\AppData\Roaming\ukmm
- Z:\Cemu-Emulator\cemu_1.26.2\graphicPacks\BreathOfTheWild_UKMM
2. Extract a new ukmm-x86_64-pc-windows-msvc folder
3. Update UKMM settings and set new file paths

This does not solve the issues with mods that can't be deleted or with **Migrate from BCML** still pointing to a very old install path: D:\Games\Cemu Emulator\Cemu Emulator Backup\mlc01\usr\title\00050000\101c9400\content
