### ISSUE TITLE
`.bas` files within custom actors are erroneously truncated when packaging

### ISSUE THREAD

**Issue by lisa-wolfgang** [NiceneNerd/ukmm#32]
This issue can be reproduced with the latest public and development builds of Second Wind.

As an example, here is `Enemy_Armos_AttackToDownShaderAlt.bas` before packaging the mod:
<details>
<summary>(click to show)</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    Elements: !list
      objects: {}
      lists:
        Element0: !list
          objects:
            Parameters: !obj
              TypeIndex: 94
              JudgeOnce: true
            Children: !obj
              Child0: 1
              Child1: 2
              Child2: 3
          lists:
            Extend: !list
              objects: {}
              lists:
                StringArray: !list
                  objects:
                    StringArray0: !obj
                      Value0: !str64 Fire
                      Value1: !str64 Electric
                      Value2: !str64 Ice
                  lists: {}
        Element1: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
        Element2: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
        Element3: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
```

</details>

And here is the file after packaging the mod:
<details>
<summary>(click to show)</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    Elements: !list
      objects: {}
      lists:
        Element0: !list
          objects:
            Parameters: !obj
              TypeIndex: 94
              JudgeOnce: true
            Children: !obj
              Child0: 1
              Child1: 1
              Child2: 1
          lists:
            Extend: !list
              objects: {}
              lists:
                StringArray: !list
                  objects:
                    StringArray0: !obj
                      Value0: !str64 Fire
                      Value1: !str64 Electric
                      Value2: !str64 Ice
                  lists: {}
        Element1: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
```

</details>

In the file in the packaged mod, `Element2` and `Element3` are completely missing, and the `Children` reference list in `Element0` points to the wrong entries in the file.

**Comment by NiceneNerd** [comment]
To clarify, this only happens to custom actors?

**Comment by NiceneNerd** [comment]
This seems to be a valid result, since all three child nodes are identical in every respect. Is this confirmed to break the actor?

**Comment by lisa-wolfgang** [comment]
Not 100% sure, but the game crashes after moving a bit in the overhauled Hateno shrine, which contains multiple Armos actors. Since moving to UKMM, CEObrainz has only noticed crashing in areas that add new enemies. This was the only difference I could find between the BCML-processed and the UKMM-processed versions of the actor.

**Comment by lisa-wolfgang** [comment]
Also double-checked and the map files for the shrine seem fully intact.

**Comment by NiceneNerd** [comment]
I've looked into it a bit, and it seems that in this case (and maybe other selector nodes?) limited node reuse is allowed, but it doesn't seem to like it if all children point to the same index. As far as I can tell this is a semantics problem anyway: it does not seem that selectors are really intended to have all outcomes lead to the same exact behavior, and I don't think this ever happens in vanilla. I could make a workaround perhaps, but I'd want to verify this is intentional and necessary in that case.

**Comment by NiceneNerd** [comment]
Actually, turns out, CEO has alerted me that the vanilla Chuchu has the same file. So I'll need to do something about this for sure to prevent all child nodes having the same index.

**Comment by lisa-wolfgang** [comment]
Thanks for addressing this so quickly! Unfortunately, that didn't seem to solve the issue -- the shrine still crashes in the exact same location.

This is what the `.bas` file from the initial example now looks like:
<details>
<summary>(click to show)</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    Elements: !list
      objects: {}
      lists:
        Element0: !list
          objects:
            Parameters: !obj
              TypeIndex: 94
              JudgeOnce: true
            Children: !obj
              Child0: 1
              Child1: 1
              Child2: 2
          lists:
            Extend: !list
              objects: {}
              lists:
                StringArray: !list
                  objects:
                    StringArray0: !obj
                      Value0: !str64 Fire
                      Value1: !str64 Electric
                      Value2: !str64 Ice
                  lists: {}
        Element1: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
        Element2: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
```

</details>

UKMM is assigning the same element to two of the child entries, which BOTW still doesn't seem satisfied with.
