### ISSUE TITLE
*.bmodellist: Mergeable ModelData_0

### ISSUE THREAD

**Issue by Benna96** [NiceneNerd/ukmm#63]
I have a mod in which I have a main model, as well as two optional models, all one actor. 
The main model should always be used, and the optional models should be used if the user picks the relevant option.

With BCML, I can make Unit_1 and Unit_2 of ModelData_0 use dummy models by default, and in the option folders change them to use* the correct models and revert the other values*. BCML generates logs with just the changes compared to vanilla, allowing to use any combination of the optional models: Neither, both, optional_1 only, optional_2 only.

I can't seem to do this on UKMM. The generated .bmodellist seems to add or replace instances of ModelData_X, it doesn't merge stuff within ModelData_X. That would be fine, I could just have ModelData_0, ModelData_1 and ModelData_2, one for each model; However, ModelData_1 and ModelData_2 aren't getting loaded, and I can't find anyone ever having mentioned their existence, making me wonder if there even is a way to make them work. Are there any vanilla files with ModelData_1 or higher?

I can of course make exclusive* options for optional_1, optional_2 & both... With the functionality being in BCML though, it should probably be in UKMM as well.

**Comment by Benna96** [comment]
<details>
<summary>Just for clarity, this is what my ModelData_0 looks like by default</summary>

```
ModelData_0: !list
  objects:
    Base: !obj
      Folder: !str64 MyModel
  lists:
    Unit: !list
      objects:
        Unit_0: !obj
          UnitName: !str64 MyModel_Main
          BindBone: !str64 ''
        Unit_1: !obj
          UnitName: !str64 MyModel_Dummy
          BindBone: !str64 ''
        Unit_2: !obj
          UnitName: !str64 MyModel_Dummy
          BindBone: !str64 ''
      lists: {}
```
</details>

<details>
<summary>This is what it looks like with optional_1</summary>

```
ModelData_0: !list
  objects:
    Base: !obj
      Folder: !str64 MyModel
  lists:
    Unit: !list
      objects:
        Unit_0: !obj
          UnitName: !str64 MyModel_Main
          BindBone: !str64 ''
        Unit_1: !obj
          UnitName: !str64 MyModel_Optional_1
          BindBone: !str64 ''
        Unit_2: !obj
          UnitName: !str64 MyModel_Dummy
          BindBone: !str64 ''
      lists: {}
```
</details>

<details>
<summary>And with optional_2</summary>

```
ModelData_0: !list
  objects:
    Base: !obj
      Folder: !str64 MyModel
  lists:
    Unit: !list
      objects:
        Unit_0: !obj
          UnitName: !str64 MyModel_Main
          BindBone: !str64 ''
        Unit_1: !obj
          UnitName: !str64 MyModel_Dummy
          BindBone: !str64 ''
        Unit_2: !obj
          UnitName: !str64 MyModel_Optional_2
          BindBone: !str64 ''
      lists: {}
```
</details>

<details>
<summary>If both optionals are selected, it should look like this</summary>

```
ModelData_0: !list
  objects:
    Base: !obj
      Folder: !str64 MyModel
  lists:
    Unit: !list
      objects:
        Unit_0: !obj
          UnitName: !str64 MyModel_Main
          BindBone: !str64 ''
        Unit_1: !obj
          UnitName: !str64 MyModel_Optional_1
          BindBone: !str64 ''
        Unit_2: !obj
          UnitName: !str64 MyModel_Optional_2
          BindBone: !str64 ''
      lists: {}
```
</details>

If there is another way to do this, I'm all ears of course.

**Comment by NiceneNerd** [comment]
What does it look like merged?

**Comment by Benna96** [comment]
The ModelData_0 section looks the way I posted in my previous message when merged. Sorry I was unclear.  
With no options selected, the section looks like the first one. With only optional_1 selected, like the second one. With only optional_2 selected, the third one. With both optional_1 and optional_2 selected, the fourth one.

<details>
<summary>Because BCML makes logs based on comparisons to vanilla files, rather than the base file in the mod itself, the source files for the options are the vanilla file + the option change. The ModelData_0 section for the source file for optional_2 for example looks like this in BCML (based on PauseMenuPlayer in this case, which uses the Link model by default):</summary>

```
ModelData_0: !list
	objects:
		Base: !obj
			Folder: !str64 Link
	lists:
		Unit: !list
			objects:
				Unit_0: !obj
					UnitName: !str64 Link
					BindBone: !str64 ''
				Unit_2: !obj
					UnitName: !str64 MyModel_Optional_2
					BindBone: !str64 ''
			lists: {}
```  
optional_2 needs to replace Unit_2, because if both optionals were occupying Unit_1, they would overwrite each other, just to make that clear. I haven't tested whether the game likes having a Unit_0 and Unit_2 without a Unit_1 present, which is why I added the dummy models for now. BCML's log generator doesn't care, and the result is fine.
</details>

<details>
<summary>The full merged bmodellist, with both options selected, looks like this, for example (again, based on PauseMenuPlayer in this case):</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects:
    ControllerInfo: !obj
      452881839: true
      MulColor: !color [1.0, 1.0, 1.0, 1.0]
      AddColor: !color [0.0, 0.0, 0.0, 0.0]
      2335622703: !str64 ''
      468054209: !str64 Fill
      3089169744: !str64 MapUnitShape
      2592531187: !str64 ''
      3331358099: !str64 ''
      3142504426: !str64 ''
      BaseScale: !vec3 [1.0, 1.0, 1.0]
      VariationMatAnim: !str64 ''
      VariationMatAnimFrame: 0
      VariationShaderAnim: !str64 ''
      VariationShaderAnimFrame: 0
      1528658372: !str32 Auto
      FarModelCullingCenter: !vec3 [0.0, 0.0, 0.0]
      FarModelCullingRadius: 0.0
      FarModelCullingHeight: 0.0
      CalcAABBASKey: !str64 Wait
    Attention: !obj
      IsEnableAttention: true
      LookAtBone: !str32 ''
      LookAtOffset: !vec3 [0.0, 0.0, 0.0]
      CursorOffsetY: 0.0
      AIInfoOffsetY: 0.0
      CutTargetBone: !str32 ''
      CutTargetOffset: !vec3 [0.0, 0.0, 0.0]
      GameCameraBone: !str32 ''
      GameCameraOffset: !vec3 [0.0, 0.0, 0.0]
      BowCameraBone: !str32 ''
      BowCameraOffset: !vec3 [0.0, 0.0, 0.0]
      AttackTargetBone: !str32 ''
      AttackTargetOffset: !vec3 [0.0, 0.0, 0.0]
      AttackTargetOffsetBack: 0.0
      AtObstacleChkOffsetBone: !str32 ''
      AtObstacleChkOffset: !vec3 [0.0, 0.0, 0.0]
      AtObstacleChkUseLookAtPos: true
      CursorAIInfoBaseBone: !str32 ''
      CursorAIInfoBaseOffset: !vec3 [0.0, 0.0, 0.0]
  lists:
    ModelData: !list
      objects: {}
      lists:
        ModelData_0: !list
          objects:
            Base: !obj
              Folder: !str64 MyModel
          lists:
            Unit: !list
              objects:
                Unit_0: !obj
                  UnitName: !str64 MyModel_Main
                  BindBone: !str64 ''
                Unit_1: !obj
                  UnitName: !str64 MyModel_Optional_1
                  BindBone: !str64 ''
                Unit_2: !obj
                  UnitName: !str64 MyModel_Optional_2
                  BindBone: !str64 ''
              lists: {}
    AnmTarget: !list
      objects: {}
      lists:
        AnmTarget_0: !list
          objects:
            Base: !obj
              NumASSlot: 1
              IsParticalEnable: false
              TargetType: 0
          lists:
            Partial: !list
              objects:
                Partial_0: !obj
                  Bone: !str32 Face_Root
                  BindFlg: 3
                  Recursible: true
              lists: {}
        AnmTarget_1: !list
          objects:
            Base: !obj
              NumASSlot: 1
              IsParticalEnable: true
              TargetType: 1
          lists:
            Partial: !list
              objects:
                Partial_0: !obj
                  Bone: !str32 Root
                  BindFlg: 3
                  Recursible: true
                Partial_1: !obj
                  Bone: !str32 Face_Root
                  BindFlg: 0
                  Recursible: true
              lists: {}
        AnmTarget_2: !list
          objects:
            Base: !obj
              NumASSlot: 1
              IsParticalEnable: false
              TargetType: 2
          lists: {}
```
</details>
