### ISSUE TITLE
`.bas` files within vanilla actors are erroneously truncated when packaging

### ISSUE THREAD

**Issue by lisa-wolfgang** [NiceneNerd/ukmm#78]
On the latest commit of UKMM and the latest development build of Second Wind, unmodified vanilla files are being changed and included in the output graphics pack. Such changes are causing the game to crash when the files are loaded. One confirmed instance is `content/Actor/Pack/Enemy_Chuchu_Senior.sbactorpack/AS/Enemy_Chuchu_AttackToDownShaderAlt.bas`, where the way UKMM modifies the file is the same as the behavior that https://github.com/NiceneNerd/ukmm/commit/a73d9f18d85463ad6a8bb7694ed60a3b9f7c9d21 fixed, only with vanilla files instead of modded files.

Vanilla (working) file:
<details>
<summary>(click to show)</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    Elements: !list
      objects: {}
      lists:
        Element0: !list
          objects:
            Parameters: !obj
              TypeIndex: 94
              JudgeOnce: true
            Children: !obj
              Child0: 1
              Child1: 2
              Child2: 3
          lists:
            Extend: !list
              objects: {}
              lists:
                StringArray: !list
                  objects:
                    StringArray0: !obj
                      Value0: !str64 Fire
                      Value1: !str64 Electric
                      Value2: !str64 Ice
                  lists: {}
        Element1: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
        Element2: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}
        Element3: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}

```

</details>

File after being processed by UKMM:
<details>
<summary>(click to show)</summary>

```
!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    Elements: !list
      objects: {}
      lists:
        Element0: !list
          objects:
            Parameters: !obj
              TypeIndex: 94
              JudgeOnce: true
            Children: !obj
              Child0: 1
              Child1: 1
              Child2: 1
          lists:
            Extend: !list
              objects: {}
              lists:
                StringArray: !list
                  objects:
                    StringArray0: !obj
                      Value0: !str64 Fire
                      Value1: !str64 Electric
                      Value2: !str64 Ice
                  lists: {}
        Element1: !list
          objects:
            Parameters: !obj
              TypeIndex: 62
              FileName: !str64 ChemicalExtinguish
          lists:
            Extend: !list
              objects: {}
              lists:
                FrameCtrl: !list
                  objects:
                    FrameCtrl0: !obj
                      EndFrame: 30.0
                      AnmLoop: 1
                  lists: {}

```

</details>

Related: #32

UKMM version: https://github.com/NiceneNerd/ukmm/commit/252e891c1cb32bb52023bdb92cd739c464d98a87 (also affects earlier versions)
Operating system: Ubuntu 22.10
